# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13SlHqbxJ2qbToII3Pa5K5h6kV-pdyDLy
"""

"Analise exploratoria dos dados brutos encontrados na tabela 2 do artigo 'Inspecionar ou testar? Qual abordagem oferece melhores resultados quando se trata de usabilidade e experiência do usuário?'"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings

warnings.filterwarnings('ignore')

dados_inspecao = {
    'Participante': ['I1', 'I2', 'I3', 'I4', 'I5', 'I7', 'I8', 'I9', 'I10'],
    'Total_Problemas': [19, 18, 25, 26, 15, 34, 27, 23, 16],
    'Tempo_min': [108, 94, 101, 81, 98, 111, 96, 114, 92],
    'Eficacia_pct': [15.0, 14.2, 19.7, 20.5, 11.8, 26.8, 21.3, 18.1, 12.6],
    'Eficiencia_pct': [10.6, 11.5, 14.9, 19.3, 9.2, 18.4, 16.9, 12.1, 10.4]
}

dados_teste = {
    'Participante': ['U1', 'U2', 'U3', 'U4', 'U5', 'U6', 'U7', 'U8', 'U9', 'U10'],
    'Total_Problemas': [11, 8, 13, 5, 8, 7, 14, 7, 9, 7],
    'Tempo_min': [33, 25, 69, 15, 30, 20, 29, 27, 57, 39],
    'Eficacia_pct': [8.7, 6.3, 10.2, 3.9, 6.3, 5.5, 11.0, 5.5, 7.1, 5.5],
    'Eficiencia_pct': [10.0, 9.6, 5.7, 10.0, 8.0, 10.5, 14.5, 7.8, 4.7, 5.4]
}

print("Dados de Inspecção (TUXEL):")
df_inspecao = pd.DataFrame(dados_inspecao)
print(df_inspecao)

print("\nDados de Teste (CTA):")
df_teste = pd.DataFrame(dados_teste)
print(df_teste)

colunas_vars = ['Total_Problemas', 'Tempo_min', 'Eficacia_pct', 'Eficiencia_pct']

desc_inspecao = df_inspecao[colunas_vars].agg(['mean', 'std']).T
desc_inspecao.columns = ['Média', 'Desvio Padrão']

desc_teste = df_teste[colunas_vars].agg(['mean', 'std']).T
desc_teste.columns = ['Média', 'Desvio Padrão']

print("Descrição dos Dados de Inspecção (TUXEL):")
print(desc_inspecao)

print("\nDescrição dos Dados de Teste (CTA):")
print(desc_teste)

df_inspecao['Grupo'] = 'Inspeção (TUXEL)'
df_teste['Grupo'] = 'Teste (CTA)'

df_completo = pd.concat([df_inspecao, df_teste], ignore_index=True)

fig, axes = plt.subplots(2, 2, figsize=(12, 10))

variaveis = [
    ('Total_Problemas', 'Total de Problemas'),
    ('Tempo_min', 'Tempo (minutos)'),
    ('Eficacia_pct', 'Eficácia (%)'),
    ('Eficiencia_pct', 'Eficiência (%)'),
]

for ax, (col, titulo) in zip(axes.flatten(), variaveis):
  sns.boxplot(
  x='Grupo',
      y=col,
      data=df_completo,
      ax=ax,
      palette='Set2',
      hue='Grupo',
      legend=False,
      showmeans=True,
  )
  ax.set_title(f'Distribuição de {titulo}', fontsize=12, fontweight='bold')
  ax.set_xlabel('')
  ax.set_ylabel(titulo)

plt.tight_layout()
plt.show()

"""Somente no boxplot da distribuição de tempo do teste (cta) que houve outliers. Esses outliers correspondem aos participantes U3 e U9 que levaram um tempo consideravelmente superior à media do restante do grupo de testes."""

variaveis = ['Total_Problemas', 'Tempo_min', 'Eficacia_pct', 'Eficiencia_pct']

resultados_shapiro = []

for var in variaveis:
  stat_insp, p_insp = stats.shapiro(df_inspecao[var])
  stat_ut, p_ut = stats.shapiro(df_teste[var])

  resultados_shapiro.append({
      'Variável': var,
      'p-valor (Inspeção)': round(p_insp, 4),
      'Normal (Inspeção)?': 'Sim (p >= 0.05)'
      if p_insp >= 0.05
      else 'Não (p < 0.05)',
      'p-valor (Teste UT)': round(p_ut, 4),
      'Normal (Teste UT)?': 'Sim (p >= 0.05)'
      if p_ut >= 0.05
      else 'Não (p < 0.05)',
  })

df_shapiro = pd.DataFrame(resultados_shapiro)
print("Resultados do Teste de Shapiro-Wilk:")
display(df_shapiro)

"""O teste de shapiro wilk foi escolhido para verificar se os dados seguem uma distribuição normal pois ele é ideal para amostras pequenas sendo considerado o teste de normalidade mais poderoso e preciso para amostras com o n < 50. Como nossa amostra possui um n = 9 na inspeção e n = 10 no teste de usabilidade, ele seria o mais viavel para realizar a verificação.

Definição do p-valor:
*   Se p >= 0.05 (distribuição normal) utiliza-se um teste parametrico denomidado Teste t de Student
*   Se p < 0.05 (distribuição não-normal) utiliza-se um teste não parametrico, o Teste de Mann-Whitney

A verificação conclui que todas as amostras seguem uma distribuição normal, ou seja, todas as 4 variaveis serão analisadas com o Teste t de Student.


"""

resultados_ttest = []

for var in variaveis:
  stat, p_val = stats.ttest_ind(
      df_inspecao[var], df_teste[var], equal_var=False
  )

  resultados_ttest.append({
      'Variável': var,
      'Estatística t': round(stat, 3),
      'p-valor': round(p_val, 4),
      'Diferença Significativa?': 'Sim (p < 0.05)'
      if p_val < 0.05
      else 'Não (p >= 0.05)',
  })

df_ttest = pd.DataFrame(resultados_ttest)
print("Resultados do Teste t de Student:")
display(df_ttest)

"""Para interpretar o resultado do Test t é preciso saber que:
*   Se p < 0.05 então existe uma diferença estatistica significativa entre a Inspeção e o Teste de Usabilidade (CTA) assim, rejeitando a hipotese nula H0
*   Se p>= 0.05 então não há diferença significativa entre os dois metodos.

Como todos os p-valores resultaram em valores menores que 0.05, a conclusão é que há uma diferença estatisticamente significativa entre a Inspeção e o Teste de Usabilidade (CTA) em todas as 4 variáveis

Ao analisar os resultados do Teste t de Student e cruzar com as medias calculadas na estatistica descritivas podemos ver que o metodo de inspeção (TUXEL) obteve valores mais altos tanto em Eficacia quanto em Eficiencia.
"""